{{- if .Values.catalogs.commonservices -}}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.catalogs.commonservices.name }}
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-10" | quote }}
    bedrock_catalogsource_priority: '1'
spec:
  {{- toYaml .Values.catalogs.commonservices.catalog | nindent 2 }}
{{- end -}}