{{- if .Values.catalogs.ibmredis -}}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.catalogs.ibmredis.name }}
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-10" | quote }}
spec:
  {{- toYaml .Values.catalogs.ibmredis.catalog | nindent 2 }}
{{- end -}}